### ISSUE TITLE
Initial database dump

### ISSUE THREAD

**Issue by ainlolcat** [sorintlab/stolon#126]
Hello.
It is not clear from documentation how I can deploy cluster with existing database dump. 

Before we uses dump of data directory. I look into stolon sources and it seems what stolon calls initdb during start so only option - connect to master after cluster start and push data from dump created by pg_dump. Thanks in advance.

**Comment by sgotti** [comment]
@ainlolcat We should add more documentation on "stolonizing" an existent database (without doing pg_dump/restore). It's difficult to automate it since there can be many different configurations types (different paths, symlinks, incompatible postgres parameters, pg_hba ecc.,.) and stolon, to correctly manage postgres parameters, pg_hba etc... needs its own kind of configuration (will automatically create it on the first initdb).

But we can define some guidelines to help user migrate current databases without doing a pg_dump/restore.

These should be the primary steps (but there are many variables):

* Start with an empty clusterview (no stolon data for your cluster inside the store (etcd/consul)) or use a new clustername (we should also add some doc on how to delete an existing cluster) and no stolon keepers/sentinels running.

* Copy the current postgres datadir under `$stolondatadir/postgres` (actually this probably can't be a symlink).

* Move the current `postgresql.conf` to `postgresql-base.conf` (the keeper will create a new `postgresql.conf` that will include it).

* Add these entries to the current `pg_hba.conf`:
```
# "local" is for Unix domain socket connections only                            
local   all             all                                     trust           
# IPv4 local connections:                                                       
host    all             all             127.0.0.1/32            trust           
# IPv6 local connections:                                                       
host    all             all             ::1/128                 trust           

host all all 0.0.0.0/0 md5
host all all ::0/0 md5
host replication repluser 0.0.0.0/0 md5
host replication repluser ::0/0 md5
```
These are currently needed for database connection from the keeper and for replication (in future they will be probably tightened).

* Ensure that you have a superuser role with the same name of the os user running the stolon-keeper/postgres instance or create it (also this in future should become a configuration option).

* Create the replication role:
`create role "repluser" with login replication encrypted password 'replpassword';`
These are the default replication role name/password defined in the default cluster config.

* Start the sentinel(s), they should create the initial cluster view and wait for an available keeper.

* Start the first stolon keeper. It should find the database as already initialized and not do an `initdb`. If there're some errors in the logs they should be investigated. The keeper should be elected as the master from the leader sentinel.

* Just start other keepers (with empty datadir), they will start syncing from the master.

Please let us know if this works for your use case or if you encounter any problem.

**Comment by ainlolcat** [comment]
Thank you. I quite sure I tried such approach but slightly different. May be I made some mistakes during image creation. I will try it again.

**Comment by ainlolcat** [comment]
I tried to reproduce initdb call but was not able to. I suppose it was my error. Thank You for your assistance.

**Comment by sgotti** [comment]
With #183 it's easy to start with a previous db backup also taken from a db cluster not under stolon control. I'm going to close this and if you have the time to test the new features please open any issue you are encountering.
