### ISSUE TITLE
stolon in multi-master consul environment

### ISSUE THREAD

**Issue by kak-tus** [sorintlab/stolon#156]
Hello,
I started to testing stolon+consul and have this issue:

I have three datacenter (dc1,dc2,dc3) with consul masters in each DC. This masters form single consul cluster, but each master has its own kv storage.
stolon uses kv consul storage to exchange data with other stolon instances.
So, I need to set store-endpoints to one of the consul datacenter (as example dc1).
After that stolon cluster works correctly.

But in this case we don't have fault tolerance: in case of dc1 fault, stolon in dc2,dc3 can't exchange data thru dc1 and can't select leader.

**Comment by sgotti** [comment]
@kak-tus A stolon cluster needs and underlying kv store, so if this kv store can span multiple datacenters then it'll also do this. So there's nothing we can do on this.

The consul kv store is per "datacenter" (IMHO correctly since a consistent store like it requires a quorum and this will be challenging with multiple datacenters and the connectivity problems that may happen between them). Of course if you can assume that your datacenters are very reliable and will never break connectivity between them (or at least less then the quorum) them you can consider them like an unique datacenter and just create an unique consul cluster (but I'll never suggest this and keep any datacenter as a seprate unit, for example k8s does cluster federation between multiple datacenters)

P.S. In the next release we're going to implement #157 that will let you define a "standby" stolon cluster that can be used for easier disaster recovery between multiple datacenters (of course you have to externally promote "standby" cluster).

**Comment by kak-tus** [comment]
Thank you, it is a great idea.
