### ISSUE TITLE
Implement a stricter synchronous standby mode to avoid choosing a not fully synced standby.

### ISSUE THREAD

**Issue by sgotti** [sorintlab/stolon#173]
Currently the synchronous standby mode set in `synchronous_standby_names` are all the defined standbys.
So it may happen that if both the master and the synced standby goes down another standby that cannot be fully in sync can be elected as the master (losing some transactions).

We can add an option to enable a stricter logic. In this logic the synchronous standby(s) are choosed by the sentinel so the keeper will set only them among all the available standbys. With potstgres <=9.5 it will be only one standby while with postgresql >= 9.6 more than one could be defined.

In this way the sentinel knows which are the standby(s) that are in real sync and when the master fails it'll choose one of them. Instead if the master and all the synced standbys goes down the sentinel won't choose another available standby (that cannot be in sync) but wait for one of them to come back.

**Comment by z0rb1n0** [comment]
Hello Simone.

This is very good for synchronous replication, which in my experience is desirable only in a minority of cases.
When it comes to promotion of one among many asynchronous slaves - a common use case -, there is a possible race condition I couldn't find any code for:

It seems to me that when retrieving the WAL lag of a standby you're not calling pg_xlog_replay_pause() for the duration of the sweep.
This unfortunately opens a window for one of the remaining standby nodes to run ahead of the one you're promoting by the time the scan is complete (EG: due to buffered network traffic, or some partitioning situations), causing them to reject WAL records from the new master.

On 9.5+ it'd be possible to use pg_rewind afterwards, but that sounds like a lot of unnecessary complexity to automate when you can prevent the problem in the first place (do you already do that?).

Am I missing something?

Cheers

**Comment by sgotti** [comment]
@z0rb1n0 I think that your question deserves its own discussion. The best place will be the (just created) [stolon mailing list](https://groups.google.com/forum/#!forum/stolon) or, if this is an issue you're encountering, just open a new one. Thanks!

**Comment by sgotti** [comment]
Resolved in #219
