### ISSUE TITLE
Ability to provide additional initdb parameters

### ISSUE THREAD

**Issue by kedare** [sorintlab/stolon#179]
Hello,

I'm currently trying Stolon with Kubernetes.

Everything works fine, but I would like to know if there is a way to pass parameters to initdb ?
I was surprised to see that the cluster is initialized using ASCII, I would like to create it with UTF-8 everywhere.

What is the way to do this ?

Thanks.

**Comment by sgotti** [comment]
@kedare Are you using the kubernetes example docker image?

initdb by default chooses the locale from the inherited environment variables. 
In this case the fedora docker image has LANG=C so initdb will use it

You can fix this in different ways:
* Change the examples run scripts to export your locale (preferred)
* When creating your db (not the postgres db) define the locale information in the `CREATE DATABASE` statement (preferred)
* Change postgres parameters with your locale.

Adding an option to provide additional initdb parameter could be done but wasn't a big requirement given the above (but if there's a big need we can add it).

**Comment by smkingsoft** [comment]
I also need provide additional initdb parameter too.
such as change language from ASCII to UTF-8

**Comment by sgotti** [comment]
@smkingsoft Isn't it possible with the proposed solutions (https://github.com/sorintlab/stolon/issues/179#issuecomment-258442371)?

Can you describe your use case and which initdb parameters you have to change? Only chaning the locale or also other parameters? Just trying to understand if this really needs to be implemented in stolon or doing this by changing the environment variables is enough. Thanks.

**Comment by smkingsoft** [comment]
@sgotti  
hi, u can see this url [#272](https://github.com/sorintlab/stolon/issues/272)
language support can doing by changing environment, but use -E or --encoding maybe more friendly.
and i also need append -k(--data-checksums)  to ensure data safety.

**Comment by sgotti** [comment]
@smkingsoft You're right. We need some options for this parameters. 

Adding an option to just set additional parameters to pass to initdb won't work since some cannot be changed will make stolon don't work (for example the pg_hba related ones) and if an user passes wrong options or overrides the ones set by stolon (like the pgdata dir) will cause strange behaviors and failure initializing a database.

My proposed solution is to add specific option for the initdb options that makes sense. The options I can see are few:

`DataChecksums` (boolean)
`Encoding` (string)
`Locale` (string)

In addition, are the various specific locale options (lc-collate, lc-numeric etc...) really required or will `Locale` be enough?

Validating the encoding and the locale may become difficult so I'll left this open and if a wrong value is passed the initialization will fail.

The other options are related to the initial pg_hba.conf so they shuld be left out (there's an open issue for customizing ph_hba.conf: #110 ).

**Comment by smkingsoft** [comment]
That's perfect!
In most scenes, i think that Locale is enough.
Maybe u can validate the encoding based on [CHARSET-TABLE Server Column](https://www.postgresql.org/docs/9.6/static/multibyte.html#CHARSET-TABLE) lists.

**Comment by sgotti** [comment]
Created #336

**Comment by sgotti** [comment]
Fixed by #338
