### ISSUE TITLE
Proxy listening on POD_IP will cause issues with port-forward of kubectl

### ISSUE THREAD

**Issue by YvanDaSilva** [sorintlab/stolon#184]
At the moment the docker image built for stolon enforces the listening ip address of the proxy to $POD_IP as shown in the following bash code:
https://github.com/sorintlab/stolon/blob/master/examples/kubernetes/image/docker/run.sh#L28

It would be better to make this optional and still let the user decide on which IP to listen.

An example where forcing the networking interface is a bad idea:
- Deploying on kubernetes
- Trying to "kubectl port-forward theproxy 5432:5432" 
- Trying to connect on expected localhost:5432 on the dev machine.

This results in a connection failure as the Proxy (go net tcp) is only listening on the containers IP and not localhost.

I could solve this issues simply by removing this line an rebuilding the container image and set the listening IP on the yaml file of the proxy.
If you see the need of being able to listen to the pod ip istelf, I would instead provide a env variable enabling this instead of enforcing it.

The proxy container is only reachable through a service, and by so listening on 0.0.0.0 by default should not be a security issue.

Best regards,
Yvan

**Comment by sgotti** [comment]
@YvanDaSilva Thanks for reporting this. Historically the stolon proxy code inherited the same code of the keeper and the keeper has the need of a fixed ip address since the sentinel needs to call it. But we are going to remove this requirement like already done just today for the sentinel in #178 implementing a store only based communication between the stolon components.

So I think we could just change the kubernetes example to make the proxy listen on INADDR_ANY, we should also remove the proxy listen address and port from the `stolonctl status` output since it doesn't have a great sense and for the same reason remove this information from the reported proxy infos (https://github.com/sorintlab/stolon/blob/master/pkg/cluster/member.go#L111-L112).

Will open a PR. Thanks!

**Comment by sgotti** [comment]
@YvanDaSilva opened #185 and #186.

**Comment by sgotti** [comment]
This has been implemented in #185 and #186.

@YvanDaSilva feel free to reopen if something is missing.

**Comment by YvanDaSilva** [comment]
Thank you, sorry I went in holidays didn't saw your work before.
Nice!
