### ISSUE TITLE
Suggestion to setup Stolon in Amazon ECS and Amazon ALB

### ISSUE THREAD

**Issue by pilgrim2go** [sorintlab/stolon#246]
@sgotti : Stolon is amazing. Since we're heavily using ECS, do you have any recommend for setting it up in ECS ?
How to organize proxy ( or workers) to run behind ALB etc?

I'd appreciate your advice since we're evaluating using Stolon in production.

**Comment by sgotti** [comment]
@pilgrim2go We have deployed different stolon cluster on AWS but unfortunately haven't done this on ECS (we are usually using kubernetes).

It shouldn't be difficult. The main points that comes to my mind are:

* The keeper requires a persistent volume so you should attach and tie an ebs for evey keeper instance (we haven't tried using an EFS we the keepers). The sentinels and proxies don't need a persistent volume.
* The proxies can be load balanced using an ALB since they are simple layer4 proxies without any logic other than connecting to the master and disconnecting from unelected masters.
* You need an high available store like etcd or consul since when it become unavailable the proxies will drop all the connection because they can't know if they are partitioned and pointing to a wrong master.

I'm not sure if the docker image coming from the [kubernetes](https://github.com/sorintlab/stolon/blob/master/examples/kubernetes/README.md) or created with the [docker](https://github.com/sorintlab/stolon/tree/master/examples/docker) example may be used as is or need some changes.

I hope someone else can jump and give some suggestions and if you manage to make it work please let us know so we can add some documentation.

**Comment by pilgrim2go** [comment]
Thanks @sgotti : I'm to try it myself and let you know

**Comment by jwickens** [comment]
Some suggestion on how to setup ETCD would be great. I'm using KOPS which has its own etcd cluster, but i setup a separate one for stolon using this helm chart as a template: https://github.com/kubernetes/charts/tree/master/incubator/etcd

However I then has this issue on restarting: https://github.com/kubernetes/charts/issues/1081. Clearing the 3 persistent volumes worked but then I had to run the cluster initialise job again.

Now I am thinking that I should use etcd-operator https://github.com/coreos/etcd-operator

What are other people doing? What are the durability requirements of that etcd cluster ?

**Comment by chriswessels** [comment]
@jwickens I'm using the etcd-operator and it's been fantastic so far.

**Comment by theothermike** [comment]
Just be aware that the backup feature of etcd-operator won't work for you since it only backs up v3 api data, not v2 as stolon is still using

**Comment by sgotti** [comment]
@jwickens inside kubernetes we use a statefulset of 3 etcd replicas with persistent volumes, the most similar approach to a "bare metal" etcd cluster.

@jwickens @theothermike @chriswessels I think this should be documented better and I'll open a PR for this: if you lose your etcd cluster (for example 2 of 3 etcd node failed and you know that they will never come back) don't restore from a backup since it will contain data probably older than the current state causing problems with the cluster due to two different time views (the clusterdata in the store and the keeper state). For example if a new master is elected and then you restore etcd with a backup containing an old stolon clusterdata where the master is defined as the old master yout cluster will probably misbehave and bad things will happen. The best solution for such cases is to [reinitialize the cluster with init mode existing](https://github.com/sorintlab/stolon/blob/master/doc/initialization.md#initialize-a-new-stolon-cluster-using-an-existing-keeper).

For the above reason I won't enable etcd-operator automatic restore on loss of quorum.

**Comment by sgotti** [comment]
@jwickens @theothermike @chriswessels created #320 to add more insights on the stolon architecture and requirements that also explains the possible problems caused if you restore the store data from a backup.

As an important note (I haven't added it to the doc and correct me if I'm wrong) the (as of today) etcd-operator logic won't fit well with stolon since looks like it prefers availabilty over data durabilty.
For example if you stop or restart at the same time at least half of the etcd pods you'll lose you cluster since the etcd pods don't use persistent volume but empty dirs. In addition, also if it'll use persistent volumes I see another problem since etcd pods could change their addresses (this is a primary kubernetes pod concept) causing a chicken/egg problems since node won't join the cluster due to changed peer addresses but it's not possible to update a member peer address if the cluster don't have quorum. I hope that in future this will be changed and I'll try to find the time to discuss this with the etcd-operator maintainers.

If you're interested I'll blog in the next days on how we achieved a persistent etcd cluster also with etcd 3.2.X where you cannot use a dns name as a member peer address anymore. The solution is currently not the cleanest one but we don't have better choices due to this new etcd 3.2.X behavior.

**Comment by sgotti** [comment]
As promised this is a detailed post with an analysis on current solutions, their problems and how we are currently achieving a persistent etcd cluster inside k8s: https://sgotti.me/post/kubernetes-persistent-etcd/

**Comment by sgotti** [comment]
@pilgrim2go Any news on this?

**Comment by sgotti** [comment]
I think the doc has improved and provides some more example and documentation so this could be closed.
