### ISSUE TITLE
kubernates stolon-sentinel slave crashing

### ISSUE THREAD

**Issue by naarani** [sorintlab/stolon#252]
on kubernates (with stolon stateful) the stolon-keeper-1 keeps crashing while logging:
"cannot take exclusive lock on data dir "/stolon-data": file already locked"

I think the configuration can't work with pvc readwritemany (?) and all the stolon-keepers are working on the same directory (!)

**Comment by sgotti** [comment]
@naarani That's a wanted check since every keeper needs its own datadir and exclusive access to it.

Are you defining the same persistent volume for all the keepers?

Can you provide some more Info's on you k8s configuratiom (are you using nfs for the persistent volumes) and the yaml files used to deploy the stolon keepers inside k8s?

**Comment by sgotti** [comment]
@naarani news on this?

**Comment by naarani** [comment]
Sorry, I've not seen the message 'till now.

I've only an NFS server as persistent volume keeper, so I've changed the yaml file to support it.

I've added an ENV called VOL-SUB (pointint to metadata to get pod name), then I've changed the run script to point to  /stolon/$VOL_SUB/stolon-data instead of /stolon/stolon-data

It works, but next time I think it will be simpler to add a sub to volume mount, something like
        volumeMounts:
        - mountPath: "/directory"
          subPath: nameFromPodMetatada
          name: volume
