### ISSUE TITLE
Stolon cluster recovery in kubernetes

### ISSUE THREAD

**Issue by sergik** [sorintlab/stolon#253]
Hi,
We are using stolon inside the kubernetes. And we planed to backup it using lvm snapshots. What is the recomended way to recover cluster after failure with the existing snapshot?

**Comment by sgotti** [comment]
@sergik In a stolon cluster there're 2 kind of persistent data: the store (etcd, consul) data and the keeper's data (that contains the pg data inside a subdir). Using lvm snapshots will mean that you're backing up the different keepers data dirs at different times (since they'll be on different machines or logical volumes). So I'll not suggest to restore only one keeper data from an lvm snapshot without touching the other keepers and stores since this will cause problem because you're creating different "time partitions".

If you lose only some keeper and the cluster is healthy one of the remaining keeper will be elected as master and, instead of restoring the lost keepers, you should just recreate new keepers from scratch. 

If you lose the whole cluster you can create a new cluster restoring from a point in time postgres backup (see the [related doc](https://github.com/sorintlab/stolon/blob/master/doc/pitr.md)), if instead you want to use lvm snapshots you can restore just one keeper (the latest known master if possible) and then reinitialize the stolon cluster in existing mode: https://github.com/sorintlab/stolon/blob/master/doc/initialization.md#initialize-a-new-stolon-cluster-using-an-existing-keeper

**Comment by sgotti** [comment]
@sergik Have I answered your question? Thoughts?

**Comment by sergik** [comment]
Thank you for reply. And if we have situation when we had a cluster with configuration in etcd. And than  etcd failed and we lost cluster config but all postgres nodes and there data are in place. Is there any way to configure them back to cluster? Especially I am interested in automated one. Something like creating smth like that in configuration stolonctl init '{ "initMode": "new" }' but without forcing nodes loose there data?

**Comment by sgotti** [comment]
@sergik if you lose the etcd data (and don't have a backup to restore) you can just reinitialize your cluster with the initmode set to "existing" and specifing the keeper to use as the starting point. The specified keeper will be kept with its postgres data and the other keepers will resync with it. IMHO It's better than nothing.

See the doc [here](https://github.com/sorintlab/stolon/blob/master/doc/initialization.md#initialize-a-new-stolon-cluster-using-an-existing-keeper)

**Comment by sgotti** [comment]
@sergik I hope to have answered all your question, I'm going to close this. Next time I suggest to use gitter or the mailing list for these kind of questions.
