### ISSUE TITLE
pitr: archive_command detect if master

### ISSUE THREAD

**Issue by sajal** [sorintlab/stolon#254]
I am playing with wal-e for pitr in stolon.

The [doc](https://github.com/sorintlab/stolon/blob/master/doc/pitr.md#archive-backups) suggests

> We suggest to define your archive command script to avoid backing up the same wal from all the instances (for example doing this only when the instance is the stolon master and just removing the wal when the instance is a stolon standby).

I would put in a shell script wrapper in my `archive_command`, but how to detect if the current instance is master or follower? is there an environment variable?

I suspect this is whats causing #250

**Comment by sgotti** [comment]
My suggestion is to do this as you'll do with any postgresql config (independently if it's managed by stolon or not). For example your `archive_command` could connect to the instance and execute a `SELECT pg_is_in_recovery();` to see if it's a master or a standby.

> I suspect this is whats causing #250

I'm not sure it's the cause since the dbid of a standby is the same of the master and taking a backup from a standby is completely correct. In fact there're some architectures where people also do backups from the standbys on a disaster recovery site.

**Comment by sajal** [comment]
I see, will test out pitr again with fresh bucket. Thanks for your help.

**Comment by sajal** [comment]
It appears wal-e is already only sending WALs from primary. I don't see wal-e messages in standby's logs.
