### ISSUE TITLE
How i can change config file (my cluster in docker containers) , example change this wal_level option?

### ISSUE THREAD

**Issue by mausspb** [sorintlab/stolon#262]
How change this option in installation step ?

**Comment by sgotti** [comment]
Please look at the related documentation: https://github.com/sorintlab/stolon/blob/master/doc/postgres_parameters.md

wal_level cannot be changed since it's managed by stolon to make the replication work (now it's probably fixes to hotstandby)

Some options requires a manual instance (restarting the keeper) restart as explained in the doc.

**Comment by mausspb** [comment]
Thank you so much for the fast answer

**Comment by sgotti** [comment]
@mausspb  no problem. In future for similar question please use the bitter channel or the mailinglist: https://github.com/sorintlab/stolon#contacts

Github issue are best suited for tracking issue and enhancements more than support questions.

**Comment by mausspb** [comment]
I know, but yesterday I asked one question and did not receive a reply
