### ISSUE TITLE
Configure keeper with environment variables/standalone file

### ISSUE THREAD

**Issue by czernitko** [sorintlab/stolon#287]
Hi, is it possible to execute stolon-keeper so that it takes configuration from either environment variables or from the config file?
I don't like idea of passing superuser password to stolon on command line, because anyone capable of running "ps aux" on the machine can see the password in plaintext.
I have searched the documentation, but foundly only stolonctl to take configuration from env variables. I have tried using the same or similarly named variables (ie. STOLON_KEEPER_CLUSTER_NAME), but they don't seem to work. I can control access to the files defining env variables, or if I could use one config file with limited read access and pass it to stolon-keeper, it would work too.
Am I just missing something, or is it not possible to pass the passwords to stolon-keeper in any other way than from the command line?
Many thanks for any help!
Peter

**Comment by sgotti** [comment]
@czernitko You can use env variables for every command, the prefixes are: STKEEPER, STSENTINEL, STPROXY, STOLONCTL. 

To avoid putting passwords in the cmdline you can use env vars but they can be retrieved with a `cat /proc/$PID/environ`, so I'll suggest to use `--pg-*-passwordfile` as described here: https://github.com/sorintlab/stolon/blob/master/doc/pg_rewind.md

You can take a look at how they are used in the k8s and docker examples.

We should probably document this better.

**Comment by sgotti** [comment]
@czernitko I opened #321 to better document command invocation and how user define environment variables in place of commnad line options. To provide passwords the suggested solution is to use the `--pg-*-passwordfile` as explained in the previous comment.

I'm going to close this as resolved if you don't have additional questions when #321 will be merged.

**Comment by czernitko** [comment]
@sgotii sorry I didn't come back to you. Thank you very much for your explanation, I have already started using those. It would be nice though to have --pg-su-* options mentioned in the new commands_invocation.md section :)

**Comment by ragaar** [comment]
Before diving into my observations, I want to prefix this is a question. There may be an error captured below, but I know I can resolve whatever issues I'm having by writing my own `entrypoint`.

However, writing an `entrypoint` throws up a red flag in my mind. What would be helpful, for me, is a list of all of the environment variables that I can tag that would be alternatives to the command-line parameters. When I find the variables, like `STKEEPER_DATA_DIR` will replace `--data-dir`, they work great and as expected. But finding the variables is a bit of a mess because they're captured all over the place.

I've actually found the yaml files available within the ".../examples/kubernetes" folder to be the most useful. For projects like this, I'm used to finding all of these variables captured (even if they're empty) within a top-level `dockerfile`.

---
| Useful | Info |
| :-- | :-- |
| Docker version | 17.05.0-ce, build 89658be |
| IMAGE | sorintlab/stolon:master-pg9.6 |

---
Something worth noting:
I'm attempting to specify a password for the replication user using the
`STOLON_KEEPER_PG_REPL_PASSWORDFILE` variable but I'm getting an error; e.g.,
>  one of --pg-repl-password or --pg-repl-passwordfile is required

From my perspective Stolon (v0.6.0) requires me to define the replication password and will not accept an environment variable with the "file" flag -- as referenced at in the [URL](https://github.com/sorintlab/stolon/blob/master/doc/pg_rewind.md) mentioned [earlier](https://github.com/sorintlab/stolon/issues/287#issuecomment-304262521).

Maybe I'm using the wrong environment variable name?

If I need to open a new issue let me know, it isn't my intention to hijack the discussion towards something that is off-topic.

**Comment by sgotti** [comment]
@ragaar 
> I'm attempting to specify a password for the replication user using the
> STOLON_KEEPER_PG_REPL_PASSWORDFILE variable but I'm getting an error; e.g.,

it should be STKEEPER_PG_REPL_PASSWORDFILE

> What would be helpful, for me, is a list of all of the environment variables that I can tag that would be alternatives to the command-line parameters

All the command flags can be provided as environment variables not just some of them and the rule is the one provided in the doc: https://github.com/sorintlab/stolon/blob/master/doc/commands_invocation.md

I was thinking that doc was enough without providing the full list of options and related env vars names (that adds some effort to keep them in sync with the commands) but if this is not the case I'll happily accept a PR to add to that doc all the command flags description with their related env var.

**Comment by ragaar** [comment]
Yeah, I completely understand the scaling issues.
I like that approach, can consider my question is satisfied :)

**Comment by sgotti** [comment]
@ragaar good. Please open a PR if you want to improve the doc.

Closing since this is addressed by #321.
