### ISSUE TITLE
How to deploy stolon to old style infrastructures

### ISSUE THREAD

**Issue by bigfanofcpp** [sorintlab/stolon#313]
How to deploy stolon to old style infrastructures?
any documents?
any installation guide?

**Comment by sgotti** [comment]
@bigfanofcpp we probably should document it better but there're can be multiple kind of deployment depending on you requirements so it's difficult to cover. I'll suggest that you understand the stolon architecture so you can play with it and design you best deployment.

Some basic notes:

The etcd/consul store will require at least 3 nodes to be high available and could live outside your stolon cluster (preferred) or inside it (we avoid the latter to not tie stolon nodes problem with store node problems, for example I/O problems)

For the stolon components the basic kind is a two machine cluster both running a stolon-keeper, a stolon-sentinel and a stolon-proxy. Your clients must call the proxies IPs. Since, usually, postgres clients/libraries can accept only one ip you should put a load balancer to balance between active proxies (if a proxy dies the lb will notice and only balance to the active proxy) or other kind of virtual IPs like keeperalived (so you'll use just one of the two proxies).

A more complex (and not always worth) architecture can host every stolon component with multiple instances on dedicated nodes.

**Comment by colin-lee** [comment]
thank you, this guide help us.

**Comment by colin-lee** [comment]
we deploy stolon on 12 vms: 
etcd 3 vms
proxy 3 vms
sentinel 3vms
keeper 3vms.
It works!

**Comment by colin-lee** [comment]
can we use synchronization with such configuration:
1 master, 1 sync standby, 1 async standby (locate in remote datacenter).

**Comment by sgotti** [comment]
@colin-lee Thanks for sharing your deployment! I'd like to add some docs on different kind of real life deployments like yours. How are you load balancing the stolon proxies?

**Comment by colin-lee** [comment]
we use lvs for stolon proxies

**Comment by sgotti** [comment]
#552 Provides some examples covering this question. I think this could be closed
