### ISSUE TITLE
Setting up Stolon in GCE (problem with minikube though)? 

### ISSUE THREAD

**Issue by Sharor** [sorintlab/stolon#333]
Hi, 

I used stolon a very long time ago to run an app in Kubernetes, and it has served me extremely well although that version is very old (2.3.x or so?). Exellent project :slightly_smiling_face: 

However now I want to try with the newer version, which utilizes stolonctl to init the cluster and Im having a bit of an issue :) 

The steps I went through (examples/kubernetes/statefulset): 
- Minikube start (kubernetes v1.7, minikube v0.21.0) 
- Deploy etcd cluster from https://github.com/coreos/etcd-operator#create-and-destroy-an-etcd-cluster (This step is probably the problem, but I need an etcd endpoint from inside the cluster, as it'll be on the google cloud - I would love if you could supply the code you use to deploy your etcd otherwise :slightly_smiling_face: )
- Change ST${COMPONENT}_STORE_ENDPOINTS to the internal client-service endpoint (10.0.0.x) for statefulset/stolon-keeper/sentinel/proxy.
- Run ./stolonctl --cluster-name=kube-stolon --store-backend=etcd --store-endpoints=10.0.0.204 init
- Get error: cannot get cluster data: client: etcd cluster is unavailable or misconfigured

To deploy it to the GCP, the same would apply as with minikube though - the etcd needs to be cluster internal, and as I could understand the etcd and the stolonctl are executed on the local machine? 

Any feedback is appreciated :wink:

**Comment by sgotti** [comment]
@Sharor the mailing list is a better place to ask for support: https://groups.google.com/forum/#!forum/stolon (this github issue tracker is for talking about reproducible issues or feature requests).

I'll try to give a fast answer but if this doesn't answer or resolve your problem can you please close this and write to the mailing list?

Your deployment should work, the problem I see is that stolonctl cannot talk with etcd. There can be many reasons.

Are you calling from an external machine? If so the reason is that the etcd service isn't probably reachable from outside. You should call it from a pod (for example exec inside a stolon component pod and run it from the inside or just run a oneshot pod).

Does the other stolon components can talk with etcd or do they report the same error? If so you'll probably need to setup the various etcd option based on you etcd config (use tls? etc...).

P.S. An option to skip the initial stolonctl init call is to use the sentinel `--initial-cluster-spec` option.

**Comment by Sharor** [comment]
I did it running a minikube setup, on a local machine so not calling it externally - sorry for misusing the issue then. I really appreciate the fast response!

Ill try with the initial init with --initial-cluster-spec, and use the mailing list if it doesn't solve it for me :slightly_smiling_face: 

I still think you guys should supply the etcd endpoint also if you have the time, to allow fast deployment :wink: (I know that open source takes a lot of time, no expectations! Just a nice-to-have)

Thank you !
