### ISSUE TITLE
Format of --initial-cluster-spec not documented

### ISSUE THREAD

**Issue by yagooar** [sorintlab/stolon#355]
I've been trying to provide this flag to the sentinel, but there is just not a single place I could find in your docs, that explains what needs to be passed as a value to that flag.

I'm talking about this instruction:

```
If you want to automate this step you can just pass an initial cluster specification to the sentinels with the --initial-cluster-spec option.
```

https://github.com/sorintlab/stolon/tree/4973929c441ae608e47692bae03756882b06a0bb/examples/kubernetes/statefulset

**Comment by sgotti** [comment]
@yagooar The format is the cluster spec https://github.com/sorintlab/stolon/blob/master/doc/cluster_spec.md that you will usually manage with `stolonctl update` and can see with `stolonctl spec`.

Please open a PR to improve the documentation.

**Comment by Krieke** [comment]
@yagooar Did you managed to create a file for the initial cluster configuration with stolon-sentinal --initial-cluster-spec ?
I am trying to setup a stolon HA postgres cluster within mesos DC/OS. So therefor I would like to do the cluster init etc... via stolon-sentinal and not via stolonctl.

**Comment by sgotti** [comment]
@Krieke here an example that has the same behavior of a `stolonctl init`:
```
{
        "initMode": "new"
}
```

This is obvioulsy used only if the clusterdata inside etcd doesn't exists, if it exists it's ignored.

But using this option has some downsides: i.e. If for some reasons you lose your etcd cluster and recreate it from scratch and the sentinel was started with that option, it'll reinitialize the clusterdata causing all the keepers to reinitialize. If using `stolonctl init` this won't happen and you can reinitialize your cluster with initmode existing and not lose the master data.

By the way, since the `stolonctl init` can be launched at every time, also when no stolon components are running, you can launch it just one time at the initial cluster deploy.

**Comment by Krieke** [comment]
Thx for the update. We have got a full and automated deployment working on DC/OS.

**Comment by sgotti** [comment]
@yagooar @Krieke I think this could be closed. If you think that the documentation related to this option should be improved I'll happily review a PR.

**Comment by Krieke** [comment]
@sgotti Ok for me to close
