### ISSUE TITLE
Feature request: JSON output from "stolonctl status"

### ISSUE THREAD

**Issue by charles-dyfis-net** [sorintlab/stolon#358]
At present, parsing the output from "stolonctl status" requires ad-hoc text processing.

An option to provide JSON output would permit easier parsing (with tools such as `jq`), and provide a means for future extension (by adding additional keys without changing the meaning of existing ones) that wouldn't have potential to impact existing parsers.

With upstream approval/consensus, I'm willing to do the implementation myself.

**Comment by sgotti** [comment]
@charles-dyfis-net `stolonctl status` just parses the clusterdata, so another option could be to just parse the `stolonctl clusterdata` json output that contains all the available information. This is what we usually do in our monitoring scripts or for debugging.

I'm not against providing a json output to `stolonctl status` but it I'll just be a sort of redundant and reworked/cleaned cluster data and will need to be versioned since it could change (the current status output could be improved but it's currently enough for our needs)

**Comment by charles-dyfis-net** [comment]
Using `clusterdata` makes sense to me.
