### ISSUE TITLE
How to use stolon as an active-active cluster?

### ISSUE THREAD

**Issue by guillelb** [sorintlab/stolon#364]
Hello,

I am using Stolon as a active-pasive cluster with 2 keepers, but only one is responding.
Is there any way to use it as an active-active cluster?
It would be perfect for share the load, and all the resources.

Thank you.

**Comment by sgotti** [comment]
@guillelb If you mean redirecting read only query to standbys you can do it calling directly tje standby (the proxy is for ensuring that connections are sent to the current master). if you mean sending rw transactions to multiple nodes it's not possible since vanilla postgresql is meant for single node write tx. There are other solutions based on postgresql or totally new like cockroachdb.

**Comment by sgotti** [comment]
@guillelb I hope I answered you question. I'm going to close this issue.
