### ISSUE TITLE
The restoreCommand questions

### ISSUE THREAD

**Issue by dmnord** [sorintlab/stolon#381]
I have two little questions for you.
1) Why you don't provide an ability to use restoreCommand in StandbySettings?
2) Why this parameter has to be used only in ArchiveRecoverySettings section when initMode is "pitr"?

**Comment by sgotti** [comment]
@dmnord 
> Why you don't provide an ability to use restoreCommand in StandbySettings?

`restoreCommand` is the archive restore command, so it live in ArchiveRecoverySettings: https://github.com/sorintlab/stolon/blob/master/doc/cluster_spec.md#archiverecoverysettings and doesn't makes sense to put it in StandbySettings. The standby will fetch the primary wals in "realtime" using the replication protocol.

> Why this parameter has to be used only in ArchiveRecoverySettings section when initMode is "pitr"?

Restoring archive wals is only used for point in time recovery.

What's your use case?

In future please ask such questions using the mailing list or the gitter channel: https://github.com/sorintlab/stolon#contacts

**Comment by dmnord** [comment]
My use case (which I would like probably to do) is to use restore_command and archive_cleanup_command in recovery.conf. But as I see, stolon doesn't do this and I can't understand why! What mechanism Stolon use to recover database while recovery proccess?

**Comment by sgotti** [comment]
@dmnord Sorry but I don't understand what you're asking for since , please provvide more details.

**Comment by dmnord** [comment]
In another words, why you don't use archive_cleanup_command parameter in recovery.conf in normal state?

**Comment by sgotti** [comment]
@dmnord Trying to read your mind: you have enabled archive mode and you want a way to remove archives on standbys? If so, if you aren't doing backups from the standby a solution is to set an archive_command that checks if the instance is standby and returns 0 exit code so postgres will remove the archive.

**Comment by dmnord** [comment]
> Trying to read your mind: you have enabled archive mode and you want a way to remove archives on standbys?
Yes, you're right!

> If so, if you aren't doing backups from the standby a solution is to set an archive_command that checks if the instance is standby and returns 0 exit code

I' d like to do this, but stolon controls every instance of postgresql in the cluster and if I change recovery.conf manualy on a standby, stolon rewite it next time (while changing the master for example)
So my question is Why stolon doesn't do this itself? Why stolon doesn't add restore_command and archive_cleanup_command in recovery.conf in normal state of standby (not in initMode=pitr state)?

**Comment by sgotti** [comment]
Because people have different ways to do backups. Some people executes backups from standbys while other from primary, other from both. So we don't want to force them.

Note that currently the archive command is the same for both primary and standbys and you already have to deal with this.

The solution I provided above works, you have to use a common archive command, it'll be a script that connects to local instance and checks if it's primary or standby and act differently.

If, instead of the above solution, you absolutely need to set archive_cleanup_command we could add a cluster spec option to set it (patches are welcomed) but, given the above behavior, I can't see valid reasons for it.
