### ISSUE TITLE
High Availability?

### ISSUE THREAD

**Issue by marct83** [sorintlab/stolon#390]
Having issues with High Availability. Not sure if this is expected or not. We run chaoskube to randomly kill pods to test high availability. The problem we're having is when a postgress pod is killed any postgress session that was currently connected has to reconnect and is given an error. It will reconnect if you just try the operation again but the error is what the problem is. High availability should be seamless without errors.

**Comment by charles-dyfis-net** [comment]
That's not what Stolon provides -- indeed, the only tools I've seen that offer that at all require a custom, stateful JDBC adapter, and are often more trouble than they're worth.

**Comment by sgotti** [comment]
@marct83 high availabilty means that if your primary postgres instance dies another one with all the data will be elected as the new primary. So between failover your client sessions will fail and you have to recreate them. Postgres sessions are per instance and cannot be "replicated". You have to handle such cases on the client side which IMHO is the right thing to do (you always have to handle possible errors on the client like network disconnections etc...). I'm going to close this, if you have further question please use the mailing list or gitter channel since the issue tracker is for bugs and feature requests: https://github.com/sorintlab/stolon#contacts. Thanks.
