### ISSUE TITLE
Should Stolon use --data-dir as I specify it and not create additional dir inside it?

### ISSUE THREAD

**Issue by pashinin** [sorintlab/stolon#394]
### Submission type

 - Bug report

#### Stolon version

v0.7.0

### Expected behaviour you didn't see

Use existing Postgres files in `data-dir`. For example: `/var/lib/postgresql/10/main`

### Unexpected behaviour you saw

Instead Stolon creates additional folder `postgres` in `data-dir` I specify.

### Steps to reproduce the problem

Start `stolon-keeper --data-dir /var/lib/postgresql/10/main` (files of my previous Postgres

See that Stolon creates `/var/lib/postgresql/10/main/postgres` with the same structure of files inside it and obviously no databases I wanted to use from my old Postgres.

I suspect that there is a reason for that but don't know if this is necessary. It would be easier fro me to use existing data.

**Comment by sgotti** [comment]
@pashinin the datadir is the stolon datadir not the postgres one. Stolon save some data inside it and puts postgres data inside the "postgres" subdir since it has to manage it.

If your intent is to put an existing postgres db cluster inside stolon the faster way is to initialize a new stolon cluster and import you existing db (pg restore from a dump or do [pitr](https://github.com/sorintlab/stolon/blob/master/doc/pitr.md)). There're also some suggestion on how to "stolonize" an existing data dir: #126 but is should be outdated.

I'm going to close this. If you have further question (not issues) let's discuss them on the mailing list or gitter channel: https://github.com/sorintlab/stolon#contacts
