### ISSUE TITLE
ETCD size requirements

### ISSUE THREAD

**Issue by guillelb** [sorintlab/stolon#486]
Hello,

I don´t found anywhere the ETCD size requirements in the stolon documentation.

The ETCD limits are: "**_The default storage size limit is 2GB, configurable with --quota-backend-bytes flag; supports up to 8GB._**" (ETCD documentation).

In my particular case, I am using a dedicated ETCD cluster only for stolon, and It reaches 2GB in approximately 8 days.

- Have you estimated the Stolon size requirements for a production environment?

- Is there some way to delete old Stolon data stored in ETCD in order to maintain the limits?

Thank you in advance!

**Comment by sgotti** [comment]
@guillelb stolon keys just requires few KiB.

Looks like you have issue in your etcd setup since we are running it for months without any issue.

If you wan't some help to debug your issue with etcd let's use the gitter channel or the mailing list providing some data (etcd version, etcd logs etc...) so we can help you. There can be some etcd related issues but to help you we need for information to understand it.

**Comment by sgotti** [comment]
@guillelb In addition ensure that you are doing periodic compation using etcdctl or you have enabled etcd auto compaction (`--auto-compaction` option to a value different than 0 and other related options. See etcd doc). Probably you aren't doing compaction and this is the issue you are facing.

**Comment by sgotti** [comment]
Added a not about etcdv3 compaction in PR #497
