### ISSUE TITLE
Use postgres's synchronous_standby_names ANY feature to improve performance

### ISSUE THREAD

**Issue by nh2** [sorintlab/stolon#515]
### Submission type

 - Request for enhancement (RFE)

### Enhancement Description

Right now stolon sets `synchronous_standby_names` like this:

```
postgres=# SHOW synchronous_standby_names;
      synchronous_standby_names      
-------------------------------------
 2 (stolon_475da099,stolon_958f8484)
```

meaning that if 2 sync standbys are online, both must acknowledge the write before it's returned to the client.

For better performance, we could use the [Multiple Synchronous Standbys ANY](https://www.postgresql.org/docs/10/static/warm-standby.html#SYNCHRONOUS-REPLICATION-MULTIPLE-STANDBYS) feature introduced in Postgres 10.

For example, we can say

```
synchronous_standby_names = 'ANY 1 (stolon_475da099, stolon_958f8484)'
````

to mean "one of the standbys has to acknowledge the write, I don't care which", so that 2 out of 3 machines (that one machine + the master) has the write acknowledged.

This would reduce latency: Whichever the slower of the two standbys is, it will not slow down the return of the write.

**Comment by sgotti** [comment]
@nh2 I tried to explain why FIRST or ANY aren't useful and using them could cause the election of a not in sync standby in different parts of the code and in the FAQ here: https://github.com/sorintlab/stolon/blob/master/doc/faq.md#does-stolon-uses-postgres-sync-replication-quorum-methods-first-or-any

Let me know if there's something unclear or you have further suggestions (the gitter channel may be better than this issue).

**Comment by nh2** [comment]
@sgotti Ah, I hadn't seen that yet.

There's one thing I don't understand about it:

> when the master fails, won't be able to know which of the 3 standbys is really synchronous and in sync with the master

This sounds like the key problem is that when using `ANY`, e.g. ANY 2 of 3, you don't know which of the 3 is the one that's not fully up to date.

But I was hoping postgres would expose information about how far up to date a given standby is (e.g. using some increasing sequence numbers in the WAL). That way, you could ask the three standbys what their sequence numbers are, and you would find two that are equal, and one that is behind. That way you could tell which one is the one that is not fully up to date.

Does postgres not provide functionality for that? It seems the `ANY` feature would be rather useless without such functionality, even outside the scope of Stolon.

**Comment by sgotti** [comment]
> But I was hoping postgres would expose information about how far up to date a given standby is (e.g. using some increasing sequence numbers in the WAL).

You can obviously query the current wal lsn position and stolon use it in many part of the sentinel to do a lot of decision logic (it's asynchronously reported by the keepers, the sentinel doesn't talk with the postgres instances) .

>  That way, you could ask the three standbys what their sequence numbers are, and you would find two that are equal, and one that is behind. That way you could tell which one is the one that is not fully up to date.

There are some issues/difficulties in this approach:

* The first difficulty is that you cannot be sure what instance is up and what is down in a fixed point in time since this will require a synchronous view of the instances wal position (and this isn't physically possible). The master may come back, do some transactions while you declared it down and elected syncstandby1 as the new primary while instead if was the other standby the one that received these last transactions (just one of the possible cases).
  To be able to do this you should first change some parts in the sentinel to ensure that no transactions are executed on the master (telling the proxy to close connections) before electing a new master (now this is done while electing), then wait some checks to get a consistent wal lsn number from all the standbys and then elect a new master. This is complicated and will slow down new primary elections.

* What will happen when you have declared `ANY 1 (stolon_475da099, stolon_958f8484)` and one of these standbys is down? You must wait for all standbys to be active since you cannot know at which point in time one went down (it could go up and down inside the sleep interval and no one may notice this). In general for `ANY N ( M standbys) you will alway need M-N+1 sync standbys up for being able to choose that.

Currently stolon will be able to failover also with only one sync standby of M up (since the primary is waiting for an ack fro all M standbys) and you will be sure that the choosed sync standby is the most uptodate.

I'm quite sure I'm missing other possible problems/corner cases but in general I don't see this approach practical (and if you can avoid the above issues it'll be very difficult to implement and test). But if someone is willing to try this I'll review PRs.

**Comment by sgotti** [comment]
Closing since I explained why it looks like not possible.
