### ISSUE TITLE
fast role change between primary and standby clusters

### ISSUE THREAD

**Issue by frelist** [sorintlab/stolon#574]
### Submission type

 - Request for enhancement (RFE)

#### Stolon version
latest

### Enhancement Description
let say we have 2 stolon clusters in 2 openshift.  DR cluster is "stolon standby cluster" of primary cluster.

When DR cluster got promoted to primary, can we easily switch the original primary to new standby?

**Comment by sgotti** [comment]
@frelist For how postgres work this will require a resync of the old primary standby with the new primary one. It's the same as managing a standalone postgres primary + replica in case of failover.

You can do this doing PITR mode on the old primary cluster. You can also try to use pg_rewind (when possible) or rsync in your pitr restore command to speed it up.

Closing since there's not much to do on the stolon side.
