### ISSUE TITLE
noisy incomplete startup packet message due to tcp liveness check

### ISSUE THREAD

**Issue by donbowman** [sorintlab/stolon#624]
### Submission type

 - Bug report

### Environment

GKE Kubernets 1.12.5

#### Stolon version

`stolonctl version v0.13.0`

### Unexpected behaviour you saw

Every second each keeper emits this message:

`[keeper-0 stolon] 2019-03-19 01:25:34.605 UTC [2459] LOG:  incomplete startup packet `

I'm reasonably sure this is due to the liveness probe hitting postgres as a TCP connection. Howvever it fills the logs quite a bit and provides no value, it would be nice if it could be filtered out.

**Comment by sgotti** [comment]
@donbowman That's a postgres log due to the liveness probe in the stolon proxy. The solution will be to have a probe that talks the postgres protocol or just filter it out but I don't think this should be done in the keeper (postgres stderr is just set to keeper's stderr) and it depends on how you configured postgres logging (it could also log to file, syslog etc...).

**Comment by demisx** [comment]
This message currently pollutes log output when using skaffold for development, since the latter merges and redirects logs from all pods into one terminal window. Can you guys please share some ideas on how this can be resolved with a different probe or something else? Maybe checking port 8080 instead? Thank you!

**Comment by baboune** [comment]
We are facing the same issue on Azure.  And this log becomes an issue as it has a cost. 3600 * 24 =86400 logs * number of keepers generates some amount of data parsing and a non negligible cost.

Any suggestions on how to remove this log or reduce its frequency?  Can we have some PG config that would ignore this?

**Comment by sgotti** [comment]
I'm an old unix guy so the best solution is to just grep out the unwanted log... nothing more is needed.

**Comment by baboune** [comment]
Thanks for the tip.  However, it is unclear where to add this "grep out" command ?

**Comment by sgotti** [comment]
@baboune Please open a post on https://talk.stolon.io/ since this isn't really a stolon issue.

**Comment by kmoppel** [comment]
FYI - the best fix is to do yourself a favour and upgrade to Postges v12 - among other things such "ping" packets are not logged anymore there.
https://github.com/postgres/postgres/commit/342cb650e0ffc7a007a12a419be04d47da4bd8cc

**Comment by baboune** [comment]
@kmoppel We found that https://git.postgresql.org/gitweb/?p=postgresql.git;a=patch;h=342cb650e had been merged into PG12.  So we will migrate to 12. Thanks.
