### ISSUE TITLE
Why select a master from sentinels first while using k8s election?

### ISSUE THREAD

**Issue by mmpei** [sorintlab/stolon#640]
As i know there is only one sentinel working when deploying a stolon in k8s.
and from code i see stolon use kubeelection to elect a pg master. 
this realy makes me confused,  KubeElection could be used to elect a master by muilt-selectors.
so my question is why only one sentinel working when using KubeElection?

**Comment by sgotti** [comment]
@mmpei There's always one leader sentinel regardless if using k8s API, etcd or consul. This is done just to avoid multiple sentinels to concurrently trying to update the cluster data.

But please note that if you remove election having all the sentinel concurrently update clusterdata, everything will work anyway since concurrent updates will just fail due to the optimistic locking provided by the underlying store (k8s API, etcd, consul). So nothing bad will happen, just more errors in the logs. The election is just to avoid such errors.

**Comment by mmpei** [comment]
Ok, i see. thank you.
